### ISSUE TITLE
Style Transfer

### ISSUE THREAD

**Issue by LLLLLLI** [Psunshine/CS231n-Spring-2017-Assignment#1]
謝謝你的作業,對我有很大幫助.
關於風格轉換的問題,最後的圖片不是風格轉換而是利用神經網絡的某一層重構出一張與原圖相似的圖片,與風格轉換無關,你的答案是正確的,具體見論文
http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Mahendran_Understanding_Deep_Image_2015_CVPR_paper.pdf

**Comment by Shiaoming** [comment]
I'm glad this work can help you. :)
As for style transfer, it's good to hear its right and thanks your remind. I'll sort this project out at odd times.
